# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2012 Henrik Nordstrom <henrik@henriknordstrom.net>
#
# Based on some other Makefile
# (C) Copyright 2000-2003
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
obj-y	+= timer.o
obj-y	+= board.o
obj-y	+= clock.o
obj-y	+= clock_xin8i.o
obj-y	+= tzpc.o
obj-y	+= prcm.o
obj-y	+= pinmux.o
